### ISSUE TITLE
-dst 是否可以填写域名？

### ISSUE THREAD

**Issue by SHIJS1999** [badafans/SecureTCPRelay#1]

**Comment by badafans** [comment]
-dst speed.cloudflare.com:80
-dst [2606:4700:7::da]:80
包括域名以及v6的地址都支持

**Comment by SHIJS1999** [comment]
> -dst speed.cloudflare.com:80
> -dst [2606:4700:7::da]:80
> 包括域名以及v6的地址都支持

![IMG_20240816_135045.jpg](https://github.com/user-attachments/assets/837745fd-45ee-4604-aa81-81176f5d25ac)

在移动端出现了这个情况

**Comment by badafans** [comment]
termux下面不支持go的某些函数  https://github.com/termux/termux-app/issues/869
这个也容易解决，在termux下编译一个就行了
termux里面创建golang环境，按照这个readme的内容进行编译即可
