### ISSUE TITLE
cfnat问题反馈

### ISSUE THREAD

**Issue by PDxtXHd** [badafans/SecureTCPRelay#4]
抱歉，因为在频道内没找到反馈入口也没找到群链接，所以发在了这里
在使用-port 参数选择非tls端口时，会在检查ip时报http: server gave HTTP response to HTTPS client的错误
例如我用
`"cfnat-windows-amd64.exe" -delay 500 -ipnum 20 -ips 4 -num 1 -port 8080 -tls false` 运行，日志如下：
```
2024/09/30 21:06:23 正在监听 0.0.0.0:1234 并转发到 1 个目标地址，有效延迟：500 ms
本地 locations.json 已存在,无需重新下载
发现有效IP 185.146.173.62 位置信息 San Jose 延迟 567 毫秒
IP 地址 | 数据中心 | 地区 | 城市 | 延迟
185.146.173.62 | SJC | North America | San Jose | 567 ms
成功提取 1 个有效IP，耗时 66秒
2024/09/30 21:07:29 向 URL https://cloudflaremirrors.com/debian 发送请求以检查 IP 185.146.173.62 是否有效
2024/09/30 21:07:29 尝试连接 IP: 185.146.173.62, 端口: 8080
2024/09/30 21:07:30 检查 IP 185.146.173.62 时发生错误: Get "https://cloudflaremirrors.com/debian": http: server gave HTTP response to HTTPS client
```
长时间运行，检查IP的报错除了`context deadline exceeded (Client.Timeout exceeded while awaiting headers)`这样连接失败的错误外就只有上面这个报错了，跑很长时间都找不到可用ip，换成2095、80端口也是类似情况。一旦换成使用默认的443端口，或者我测试指定8443端口，则不会报错，很快就能找到可用ip。

**Comment by badafans** [comment]
-tls=false  因为是布尔型变量，go命令运行需要加上等号

**Comment by PDxtXHd** [comment]
> -tls=false 因为是布尔型变量，go命令运行需要加上等号

感谢大佬，确实是这个问题，改一下就正常了
